### ISSUE TITLE
Invalid utf8 character in index

### ISSUE THREAD

**Issue by lakemike** [simon987/sist2#44] opened 2020-04-11 12:43 UTC
Hi,
During the "index" step, I see error messages like the below.
Kind regards,
lakemike

```
[2020-04-09 10:42:25] [ERROR elastic.c] {
	"index":	{
		"_index":	"sist2",
		"_type":	"_doc",
		"_id":	"9e74c6ed-9bd8-45fd-8c7a-86c5d35c7496",
		"status":	400,
		"error":	{
			"type":	"parse_exception",
			"reason":	"Failed to parse content to map",
			"caused_by":	{
				"type":	"json_parse_exception",
				"reason":	"Invalid UTF-8 start byte 0x81\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@234889b9; line: 1, column: 136]"
			}
		}
	}
}
```

**Comment by simon987** [comment] 2020-05-08 22:31
(Sorry for the delay)
Hi @lakemike, I had originally assumed I would be able to reproduce this on my own, are you able to re-index with the latest version, and then send the contents of `sist2 index --print | grep "9e74c6ed-9bd8-45fd-8c7a-86c5d35c7496"` (with the new document id of the error)

**Comment by lakemike** [comment] 2020-05-09 10:11
Hi,

I could find out that it's probably about German umlauts in my case:
{"_id":"7d935c63-fc0c-46a0-9702-8e99cca1deec","_index":"sist2","_type":"_doc","_source":{"index":"4cf8b2f2-8844-49ad-a306-b1cf4f3a352a","mime":"application/CDFV2","size":17408,"mtime":1573380406,"extension":"msg","name":"**Autohaus B?chle**","path":"20191110-Outlook-Contacts.zip#/20191110-Outlook-Contacts","parent":"24fdcd24-890c-4470-b1db-9cb6c6dc4807"}}
It should show "ä" instead of "?".
I checked a few more and they all seem to have umlauts in the document name.
Kind regards,
Michael

**Comment by simon987** [comment] 2020-05-10 23:56
@lakemike Thanks a lot for the info!
Can you please try it again with docker image version 2.2.1 ? I wasn't quite able to reproduce the same error but I think I might have fixed it

**Comment by lakemike** [comment] 2020-05-11 11:39
Hello Simon,
Thank you for the note. Happy to help. It’s not yet solved in v2.2.1.
I’ve sent you an archive with 2 of these problematic files via email.

**Comment by simon987** [comment] 2020-05-12 23:34
The files you sent have invalid/illegal UTF-8 characters in the file name, I'm assuming it comes from another charset.

This is a tricky fix because I can't just ignore invalid characters or replace them with questions marks, because that would break the "serve from disk" feature for these files. A fix I found was to escape invalid utf8 characters when reading from the index, and un-escape them when loading from disk.

Please let me know if the files you were having problems with are correctly indexed in v2.3.0 (They probably won't display properly in the web interface no matter what)

**Comment by lakemike** [comment] 2020-05-13 07:40
These files are interesting indeed. I remember that these are Outlook contacts dragged to Desktop. However, when I tried to recreate them using latest Outlook under Windows 10, then it does not seem to be possible any longer.
Regarding your fix- This works when such files are outside archives. It would still not work for files inside archives.

**Comment by simon987** [comment] 2020-05-24 14:12
Oh, sorry about that @lakemike, there were some unrelated bugs (namely, .tgz files not being recognized as an archive).
I tested your test file and it seems to handle files inside archives correctly with v2.3.1, please let me know if this is the case, thanks!

**Comment by lakemike** [comment] 2020-05-24 16:39
Hi Simon, you may still need to push 2.3.1 to docker. I could not find it..

**Comment by simon987** [comment] 2020-05-24 16:43
Oops, sorry about that, my CI server went offline without me noticing, it should be pushed now

**Comment by lakemike** [comment] 2020-05-25 08:50
With 2.3.1-> same result as before, i.e. files that are inside archives and that have special characters in their name will not get picked up. 
With 2.3.2 -> several error messages "Guessing mime type with libmagic inside archive files is not currently supported" and even matches to file names (not content) are now missing.

**Comment by simon987** [comment] 2020-05-25 12:43
That's odd, are you testing with the same .tar file you sent me by email?

**Comment by lakemike** [comment] 2020-05-25 13:41
Yes same file, but it was a .tgz not .tar. I tested a bit more .. 
For standard character file names, v2.3.1 will show hits in .tar and .zip but not in .tgz
For special character file names, v2.3.1 will only show direct hits (using escaped characters), but never inside any archive type.

**Comment by simon987** [comment] 2020-05-25 22:44
Okay, sorry about that - I should have tested the docker image before making you test it. For some reason the commit that fixed the .tgz archives never made it to the 2.3.1 version.
And for some other reason I introduced a bug in the 2.3.2 version where all unknown file extensions inside archives are ignored (which should be fixed now).

The updated 2.3.2 image now shows both files inside .tgz archive and file outside archives, can you please confirm that it also works on your side?

Thanks!

**Comment by lakemike** [comment] 2020-05-26 09:53
Thanks! I can confirm that v2.3.2 seems to do all the right things!

**Comment by simon987** [comment] 2020-05-26 12:49
Awesome 👏

**Closed by simon987** 2020-05-26 12:49 UTC
Labels: bug, scan
