### ISSUE TITLE
MuPDF scan errors

### ISSUE THREAD

**Issue by lakemike** [simon987/sist2#43] opened 2020-04-11 09:54 UTC
Hi, 
I have a large body of office documents (pdf, docx, pptx) and I noticed that the scanner throws a lot of error messages. Typically, it will also mean that full-text search does not work for the respective document. (Some error messages shown below .. there are a lot more). How could I best help debugging the scanner?
Kind regards,
lakemike

# scan output:
..
FZ: cannot recognize xref format
FZ: trying to repair broken xref
FZ: repairing PDF document
..
FZ: invalid page object
..
Could not read archive: Unrecognized archive format
..
FZ: type3 glyph doesn't specify masked or colored
FZ: ... repeated 34 times...
..
[ERROR doc.c] Got fatal XML error while parsing document: Start tag expected, '<' not found
..

**Comment by simon987** [comment] 2020-04-11 11:32
Hi, those 'FZ' errors are from the MuPDF library and are generally not under my control, however, if you can send me a example file I might be able to find where the problem is a make a fix, you can also email me the file at me[at]simon987.net

**Comment by simon987** [comment] 2020-05-01 01:19
Hi @lakemike, thank you so much for the bug report.
I did the tests on my end and it seems to be fixed in v2.0.0, can you please confirm?

**Comment by lakemike** [comment] 2020-05-02 10:33
Hello Simon,
Thanks! This is a huge improvement because many more documents are picked up and, in fact, the whole scanning process takes much longer because much more text is scanned as a result. The document test set seems work very well now! 
Of note, however, when I scanned a larger document tree and compared with Qsirch (a search engine provided on QNAP NAS systems), I still got differences. Qsirch provides often 2x more results as compared to sist2. This may be due to more file types being supported by Qsirch (e.g. emails), but I would speculate there are more bugs to find. E.g. I was trying to find one particular document that did not show up in sist2, and noticed that it did get picked up in an isolated test directory.
-> Even more verbose scanner/indexer output (at the document level) could help to pin down remaining issues.

**Comment by simon987** [comment] 2020-05-02 22:05
You can use `sist2 index --print ./index | jq | less` to examine the output of the scan. Note that with the default options only index the first few kb of documents, (see `--content-size` option)

**Comment by lakemike** [comment] 2020-05-03 10:05
Hello Simon,
Thank you for reminding me of `--content-size`. I entered a very high number (999999999) and the new index is 2.5x larger. As much as I can see it is very comprehensive and the remaining differences may be due to emails being out of scope for sist.
Best wishes

**Comment by simon987** [comment] 2020-05-03 12:02
Thank you for the reply, out of curiosity, what is the extension and mime type of email files ? You can find the mime type on linux with `file --mime-type <file>`

**Comment by lakemike** [comment] 2020-05-03 15:42
These are Outlook emails (.msg): `application/vnd.ms-outlook`. I can see that .eml files are scanned correctly (`message/rfc822`).

**Closed** 2020-05-05 22:31 UTC
Labels: scan
